// src/app/layout.tsx
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/styles/globals.css'; // Import global styles
import { Providers } from '@/lib/providers'; // Import your Apollo Provider

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'My Next.js App with MVVM',
  description: 'Generated by create next app and customized',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers> {/* Wrap children with ApolloProvider */}
          {children}
        </Providers>
      </body>
    </html>
  );
}
